package com.myspace.serviciorestdemo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AseguradoWrapper implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private com.myspace.serviciorestdemo.Asegurado entidad;

	public AseguradoWrapper() {
	}

	public com.myspace.serviciorestdemo.Asegurado getEntidad() {
		return this.entidad;
	}

	public void setEntidad(com.myspace.serviciorestdemo.Asegurado entidad) {
		this.entidad = entidad;
	}

	public AseguradoWrapper(com.myspace.serviciorestdemo.Asegurado entidad) {
		this.entidad = entidad;
	}

}