package com.myspace.serviciorestdemo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Asegurado implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Long id;
	private java.lang.String identificacion;
	private java.lang.String nombres;
	private java.lang.String apellido;
	private java.lang.String correo;

	public Asegurado() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getIdentificacion() {
		return this.identificacion;
	}

	public void setIdentificacion(java.lang.String identificacion) {
		this.identificacion = identificacion;
	}

	public java.lang.String getNombres() {
		return this.nombres;
	}

	public void setNombres(java.lang.String nombres) {
		this.nombres = nombres;
	}

	public java.lang.String getApellido() {
		return this.apellido;
	}

	public void setApellido(java.lang.String apellido) {
		this.apellido = apellido;
	}

	public java.lang.String getCorreo() {
		return this.correo;
	}

	public void setCorreo(java.lang.String correo) {
		this.correo = correo;
	}

	public Asegurado(java.lang.Long id, java.lang.String identificacion,
			java.lang.String nombres, java.lang.String apellido,
			java.lang.String correo) {
		this.id = id;
		this.identificacion = identificacion;
		this.nombres = nombres;
		this.apellido = apellido;
		this.correo = correo;
	}

}